# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.grpc.v1 import attributes_pb2 as altastata_dot_grpc_dot_v1_dot_attributes__pb2
from altastata.grpc.v1 import users_pb2 as altastata_dot_grpc_dot_v1_dot_users__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/grpc/v1/attributes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttributesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAttribute = channel.unary_unary(
                '/altastata.v1.AttributesService/GetAttribute',
                request_serializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.GetAttributeRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.Attribute.FromString,
                _registered_method=True)
        self.GetAttributes = channel.unary_unary(
                '/altastata.v1.AttributesService/GetAttributes',
                request_serializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.GetAttributesRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.AttributeMap.FromString,
                _registered_method=True)
        self.SetAttribute = channel.unary_unary(
                '/altastata.v1.AttributesService/SetAttribute',
                request_serializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.SetAttributeRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_users__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteAttribute = channel.unary_unary(
                '/altastata.v1.AttributesService/DeleteAttribute',
                request_serializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.DeleteAttributeRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_users__pb2.Empty.FromString,
                _registered_method=True)


class AttributesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttributesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttribute,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.GetAttributeRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.Attribute.SerializeToString,
            ),
            'GetAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributes,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.GetAttributesRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.AttributeMap.SerializeToString,
            ),
            'SetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttribute,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.SetAttributeRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_users__pb2.Empty.SerializeToString,
            ),
            'DeleteAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAttribute,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_attributes__pb2.DeleteAttributeRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_users__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.AttributesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.AttributesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttributesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AttributesService/GetAttribute',
            altastata_dot_grpc_dot_v1_dot_attributes__pb2.GetAttributeRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_attributes__pb2.Attribute.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AttributesService/GetAttributes',
            altastata_dot_grpc_dot_v1_dot_attributes__pb2.GetAttributesRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_attributes__pb2.AttributeMap.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AttributesService/SetAttribute',
            altastata_dot_grpc_dot_v1_dot_attributes__pb2.SetAttributeRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_users__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AttributesService/DeleteAttribute',
            altastata_dot_grpc_dot_v1_dot_attributes__pb2.DeleteAttributeRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_users__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
