# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altastata/grpc/v1/attributes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'altastata/grpc/v1/attributes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from altastata.grpc.v1 import users_pb2 as altastata_dot_grpc_dot_v1_dot_users__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"altastata/grpc/v1/attributes.proto\x12\x0c\x61ltastata.v1\x1a\x1d\x61ltastata/grpc/v1/users.proto\"(\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x81\x01\n\x0c\x41ttributeMap\x12>\n\nattributes\x18\x01 \x03(\x0b\x32*.altastata.v1.AttributeMap.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"M\n\x13GetAttributeRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x15\n\rsnapshot_time\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t\"O\n\x14GetAttributesRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x15\n\rsnapshot_time\x18\x02 \x01(\x03\x12\r\n\x05names\x18\x03 \x03(\t\"\\\n\x13SetAttributeRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x15\n\rsnapshot_time\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"P\n\x16\x44\x65leteAttributeRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x15\n\rsnapshot_time\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t2\xc6\x02\n\x11\x41ttributesService\x12J\n\x0cGetAttribute\x12!.altastata.v1.GetAttributeRequest\x1a\x17.altastata.v1.Attribute\x12O\n\rGetAttributes\x12\".altastata.v1.GetAttributesRequest\x1a\x1a.altastata.v1.AttributeMap\x12\x46\n\x0cSetAttribute\x12!.altastata.v1.SetAttributeRequest\x1a\x13.altastata.v1.Empty\x12L\n\x0f\x44\x65leteAttribute\x12$.altastata.v1.DeleteAttributeRequest\x1a\x13.altastata.v1.EmptyB-\n\x18\x63om.altastata.grpc.protoB\x0f\x41ttributesProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altastata.grpc.v1.attributes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.altastata.grpc.protoB\017AttributesProtoP\001'
  _globals['_ATTRIBUTEMAP_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_ATTRIBUTEMAP_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_ATTRIBUTE']._serialized_start=83
  _globals['_ATTRIBUTE']._serialized_end=123
  _globals['_ATTRIBUTEMAP']._serialized_start=126
  _globals['_ATTRIBUTEMAP']._serialized_end=255
  _globals['_ATTRIBUTEMAP_ATTRIBUTESENTRY']._serialized_start=206
  _globals['_ATTRIBUTEMAP_ATTRIBUTESENTRY']._serialized_end=255
  _globals['_GETATTRIBUTEREQUEST']._serialized_start=257
  _globals['_GETATTRIBUTEREQUEST']._serialized_end=334
  _globals['_GETATTRIBUTESREQUEST']._serialized_start=336
  _globals['_GETATTRIBUTESREQUEST']._serialized_end=415
  _globals['_SETATTRIBUTEREQUEST']._serialized_start=417
  _globals['_SETATTRIBUTEREQUEST']._serialized_end=509
  _globals['_DELETEATTRIBUTEREQUEST']._serialized_start=511
  _globals['_DELETEATTRIBUTEREQUEST']._serialized_end=591
  _globals['_ATTRIBUTESSERVICE']._serialized_start=594
  _globals['_ATTRIBUTESSERVICE']._serialized_end=920
# @@protoc_insertion_point(module_scope)
