# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.v1 import auth_pb2 as altastata_dot_v1_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/v1/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Application-layer authentication for altastata-grpc.

    See altastata-grpc/SESSION_AND_EVENTS_DESIGN.md §5.

    Login validates the user's password on a transient AltaStataFileSystem
    (probe-then-install — see SESSION_AND_EVENTS_DESIGN.md §6 and PR #176)
    and issues an opaque per-tab session token of the form sess-<base64url>.
    Subsequent RPCs MUST present the token via "Authorization: Bearer <token>".

    Sessions have a sliding TTL (default 8 hours, configurable via
    ALTASTATA_GRPC_SESSION_TTL). Logout invalidates one session immediately;
    other sessions of the same user are unaffected.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/altastata.v1.AuthService/Login',
                request_serializer=altastata_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/altastata.v1.AuthService/Logout',
                request_serializer=altastata_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_auth__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/altastata.v1.AuthService/Refresh',
                request_serializer=altastata_dot_v1_dot_auth__pb2.RefreshRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_auth__pb2.RefreshResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Application-layer authentication for altastata-grpc.

    See altastata-grpc/SESSION_AND_EVENTS_DESIGN.md §5.

    Login validates the user's password on a transient AltaStataFileSystem
    (probe-then-install — see SESSION_AND_EVENTS_DESIGN.md §6 and PR #176)
    and issues an opaque per-tab session token of the form sess-<base64url>.
    Subsequent RPCs MUST present the token via "Authorization: Bearer <token>".

    Sessions have a sliding TTL (default 8 hours, configurable via
    ALTASTATA_GRPC_SESSION_TTL). Logout invalidates one session immediately;
    other sessions of the same user are unaffected.
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=altastata_dot_v1_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=altastata_dot_v1_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_auth__pb2.LogoutResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=altastata_dot_v1_dot_auth__pb2.RefreshRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_auth__pb2.RefreshResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Application-layer authentication for altastata-grpc.

    See altastata-grpc/SESSION_AND_EVENTS_DESIGN.md §5.

    Login validates the user's password on a transient AltaStataFileSystem
    (probe-then-install — see SESSION_AND_EVENTS_DESIGN.md §6 and PR #176)
    and issues an opaque per-tab session token of the form sess-<base64url>.
    Subsequent RPCs MUST present the token via "Authorization: Bearer <token>".

    Sessions have a sliding TTL (default 8 hours, configurable via
    ALTASTATA_GRPC_SESSION_TTL). Logout invalidates one session immediately;
    other sessions of the same user are unaffected.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AuthService/Login',
            altastata_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            altastata_dot_v1_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AuthService/Logout',
            altastata_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
            altastata_dot_v1_dot_auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AuthService/Refresh',
            altastata_dot_v1_dot_auth__pb2.RefreshRequest.SerializeToString,
            altastata_dot_v1_dot_auth__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
