# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altastata/v1/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'altastata/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61ltastata/v1/auth.proto\x12\x0c\x61ltastata.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n\x0cLoginRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x18\n\x10\x61\x63\x63ount_password\x18\x02 \x01(\t\x12\x13\n\x0b\x63lient_hint\x18\x03 \x01(\t\"j\n\rLoginResponse\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12.\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\naccess_key\x18\x03 \x01(\t\"\x0f\n\rLogoutRequest\"\x10\n\x0eLogoutResponse\"\x10\n\x0eRefreshRequest\"A\n\x0fRefreshResponse\x12.\n\nexpires_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xdc\x01\n\x0b\x41uthService\x12@\n\x05Login\x12\x1a.altastata.v1.LoginRequest\x1a\x1b.altastata.v1.LoginResponse\x12\x43\n\x06Logout\x12\x1b.altastata.v1.LogoutRequest\x1a\x1c.altastata.v1.LogoutResponse\x12\x46\n\x07Refresh\x12\x1c.altastata.v1.RefreshRequest\x1a\x1d.altastata.v1.RefreshResponseB\'\n\x18\x63om.altastata.grpc.protoB\tAuthProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altastata.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.altastata.grpc.protoB\tAuthProtoP\001'
  _globals['_LOGINREQUEST']._serialized_start=74
  _globals['_LOGINREQUEST']._serialized_end=154
  _globals['_LOGINRESPONSE']._serialized_start=156
  _globals['_LOGINRESPONSE']._serialized_end=262
  _globals['_LOGOUTREQUEST']._serialized_start=264
  _globals['_LOGOUTREQUEST']._serialized_end=279
  _globals['_LOGOUTRESPONSE']._serialized_start=281
  _globals['_LOGOUTRESPONSE']._serialized_end=297
  _globals['_REFRESHREQUEST']._serialized_start=299
  _globals['_REFRESHREQUEST']._serialized_end=315
  _globals['_REFRESHRESPONSE']._serialized_start=317
  _globals['_REFRESHRESPONSE']._serialized_end=382
  _globals['_AUTHSERVICE']._serialized_start=385
  _globals['_AUTHSERVICE']._serialized_end=605
# @@protoc_insertion_point(module_scope)
