# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altastata/v1/events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'altastata/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61ltastata/v1/events.proto\x12\x0c\x61ltastata.v1\"\x12\n\x10SubscribeRequest\"0\n\x0c\x45ventMessage\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2Z\n\rEventsService\x12I\n\tSubscribe\x12\x1e.altastata.v1.SubscribeRequest\x1a\x1a.altastata.v1.EventMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altastata.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=43
  _globals['_SUBSCRIBEREQUEST']._serialized_end=61
  _globals['_EVENTMESSAGE']._serialized_start=63
  _globals['_EVENTMESSAGE']._serialized_end=111
  _globals['_EVENTSSERVICE']._serialized_start=113
  _globals['_EVENTSSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
