# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.v1 import events_pb2 as altastata_dot_v1_dot_events__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/v1/events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventsServiceStub(object):
    """=============================================================================
    Real-time event delivery for altastata-grpc.

    See altastata-grpc/SESSION_AND_EVENTS_DESIGN.md §7 for the full model.

    Two RPCs live in this file:

    Watch     — NEW.  Per-session server-streaming RPC backed by EventBus.
    Each session (each browser tab / each AuthService.Login) opens
    exactly one Watch stream after Login. The server delivers a
    typed Event stream with monotonic per-userName sequence
    numbers, supports since_sequence-based replay from the
    in-memory ring buffer, and emits EventGap when the requested
    cursor is older than the buffer.

    Subscribe — DEPRECATED. The pre-EventBus path that registers a listener
    directly on AltaStataFileSystem and forwards untyped
    (eventName, data) tuples. Kept for backwards compatibility
    with the existing frontend; will be removed together with
    EventMessage / SubscribeRequest in PR-6 of the design doc.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Watch = channel.unary_stream(
                '/altastata.v1.EventsService/Watch',
                request_serializer=altastata_dot_v1_dot_events__pb2.WatchRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_events__pb2.Event.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/altastata.v1.EventsService/Subscribe',
                request_serializer=altastata_dot_v1_dot_events__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_events__pb2.EventMessage.FromString,
                _registered_method=True)


class EventsServiceServicer(object):
    """=============================================================================
    Real-time event delivery for altastata-grpc.

    See altastata-grpc/SESSION_AND_EVENTS_DESIGN.md §7 for the full model.

    Two RPCs live in this file:

    Watch     — NEW.  Per-session server-streaming RPC backed by EventBus.
    Each session (each browser tab / each AuthService.Login) opens
    exactly one Watch stream after Login. The server delivers a
    typed Event stream with monotonic per-userName sequence
    numbers, supports since_sequence-based replay from the
    in-memory ring buffer, and emits EventGap when the requested
    cursor is older than the buffer.

    Subscribe — DEPRECATED. The pre-EventBus path that registers a listener
    directly on AltaStataFileSystem and forwards untyped
    (eventName, data) tuples. Kept for backwards compatibility
    with the existing frontend; will be removed together with
    EventMessage / SubscribeRequest in PR-6 of the design doc.
    =============================================================================

    """

    def Watch(self, request, context):
        """Per-session real-time event stream. Authenticated via the standard
        Authorization: Bearer sess-... header. The userName for fan-out is
        resolved server-side from the session token; clients cannot watch
        events for another user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """DEPRECATED: untyped pre-EventBus listener path. Use Watch instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=altastata_dot_v1_dot_events__pb2.WatchRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_events__pb2.Event.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=altastata_dot_v1_dot_events__pb2.SubscribeRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_events__pb2.EventMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.EventsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.EventsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventsService(object):
    """=============================================================================
    Real-time event delivery for altastata-grpc.

    See altastata-grpc/SESSION_AND_EVENTS_DESIGN.md §7 for the full model.

    Two RPCs live in this file:

    Watch     — NEW.  Per-session server-streaming RPC backed by EventBus.
    Each session (each browser tab / each AuthService.Login) opens
    exactly one Watch stream after Login. The server delivers a
    typed Event stream with monotonic per-userName sequence
    numbers, supports since_sequence-based replay from the
    in-memory ring buffer, and emits EventGap when the requested
    cursor is older than the buffer.

    Subscribe — DEPRECATED. The pre-EventBus path that registers a listener
    directly on AltaStataFileSystem and forwards untyped
    (eventName, data) tuples. Kept for backwards compatibility
    with the existing frontend; will be removed together with
    EventMessage / SubscribeRequest in PR-6 of the design doc.
    =============================================================================

    """

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/altastata.v1.EventsService/Watch',
            altastata_dot_v1_dot_events__pb2.WatchRequest.SerializeToString,
            altastata_dot_v1_dot_events__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/altastata.v1.EventsService/Subscribe',
            altastata_dot_v1_dot_events__pb2.SubscribeRequest.SerializeToString,
            altastata_dot_v1_dot_events__pb2.EventMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
