# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.v1 import fileops_pb2 as altastata_dot_v1_dot_fileops__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/v1/fileops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileOpsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFile = channel.unary_unary(
                '/altastata.v1.FileOpsService/CreateFile',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.CreateFileResponse.FromString,
                _registered_method=True)
        self.GetBuffer = channel.unary_unary(
                '/altastata.v1.FileOpsService/GetBuffer',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.GetBufferRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.GetBufferResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/altastata.v1.FileOpsService/Delete',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.DeleteRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_stream(
                '/altastata.v1.FileOpsService/ListVersions',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.VersionEntry.FromString,
                _registered_method=True)
        self.AppendBufferToFile = channel.unary_unary(
                '/altastata.v1.FileOpsService/AppendBufferToFile',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.AppendBufferToFileRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.AppendBufferToFileResponse.FromString,
                _registered_method=True)
        self.Store = channel.unary_unary(
                '/altastata.v1.FileOpsService/Store',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.StoreRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/altastata.v1.FileOpsService/Retrieve',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.CopyFile = channel.unary_unary(
                '/altastata.v1.FileOpsService/CopyFile',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.CopyFileRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.CopyFileResponse.FromString,
                _registered_method=True)
        self.ReadStream = channel.unary_stream(
                '/altastata.v1.FileOpsService/ReadStream',
                request_serializer=altastata_dot_v1_dot_fileops__pb2.ReadStreamRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_fileops__pb2.ReadStreamChunk.FromString,
                _registered_method=True)


class FileOpsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendBufferToFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileOpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.CreateFileRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.CreateFileResponse.SerializeToString,
            ),
            'GetBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuffer,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.GetBufferRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.GetBufferResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.DeleteRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.DeleteResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_stream_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.ListVersionsRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.VersionEntry.SerializeToString,
            ),
            'AppendBufferToFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendBufferToFile,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.AppendBufferToFileRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.AppendBufferToFileResponse.SerializeToString,
            ),
            'Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Store,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.StoreRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.StoreResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.RetrieveRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.RetrieveResponse.SerializeToString,
            ),
            'CopyFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyFile,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.CopyFileRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.CopyFileResponse.SerializeToString,
            ),
            'ReadStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadStream,
                    request_deserializer=altastata_dot_v1_dot_fileops__pb2.ReadStreamRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_fileops__pb2.ReadStreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.FileOpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.FileOpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileOpsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.FileOpsService/CreateFile',
            altastata_dot_v1_dot_fileops__pb2.CreateFileRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.CreateFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.FileOpsService/GetBuffer',
            altastata_dot_v1_dot_fileops__pb2.GetBufferRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.GetBufferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.FileOpsService/Delete',
            altastata_dot_v1_dot_fileops__pb2.DeleteRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/altastata.v1.FileOpsService/ListVersions',
            altastata_dot_v1_dot_fileops__pb2.ListVersionsRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.VersionEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendBufferToFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.FileOpsService/AppendBufferToFile',
            altastata_dot_v1_dot_fileops__pb2.AppendBufferToFileRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.AppendBufferToFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.FileOpsService/Store',
            altastata_dot_v1_dot_fileops__pb2.StoreRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.FileOpsService/Retrieve',
            altastata_dot_v1_dot_fileops__pb2.RetrieveRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.FileOpsService/CopyFile',
            altastata_dot_v1_dot_fileops__pb2.CopyFileRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.CopyFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/altastata.v1.FileOpsService/ReadStream',
            altastata_dot_v1_dot_fileops__pb2.ReadStreamRequest.SerializeToString,
            altastata_dot_v1_dot_fileops__pb2.ReadStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
