# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.v1 import sharing_pb2 as altastata_dot_v1_dot_sharing__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/v1/sharing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SharingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Share = channel.unary_unary(
                '/altastata.v1.SharingService/Share',
                request_serializer=altastata_dot_v1_dot_sharing__pb2.ShareRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_sharing__pb2.ShareResult.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/altastata.v1.SharingService/Revoke',
                request_serializer=altastata_dot_v1_dot_sharing__pb2.RevokeRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_sharing__pb2.RevokeResult.FromString,
                _registered_method=True)
        self.ShareByQuery = channel.unary_unary(
                '/altastata.v1.SharingService/ShareByQuery',
                request_serializer=altastata_dot_v1_dot_sharing__pb2.ShareByQueryRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_sharing__pb2.ShareResult.FromString,
                _registered_method=True)
        self.RevokeByQuery = channel.unary_unary(
                '/altastata.v1.SharingService/RevokeByQuery',
                request_serializer=altastata_dot_v1_dot_sharing__pb2.RevokeByQueryRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_sharing__pb2.RevokeResult.FromString,
                _registered_method=True)


class SharingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Share(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareByQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeByQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SharingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Share': grpc.unary_unary_rpc_method_handler(
                    servicer.Share,
                    request_deserializer=altastata_dot_v1_dot_sharing__pb2.ShareRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_sharing__pb2.ShareResult.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=altastata_dot_v1_dot_sharing__pb2.RevokeRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_sharing__pb2.RevokeResult.SerializeToString,
            ),
            'ShareByQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareByQuery,
                    request_deserializer=altastata_dot_v1_dot_sharing__pb2.ShareByQueryRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_sharing__pb2.ShareResult.SerializeToString,
            ),
            'RevokeByQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeByQuery,
                    request_deserializer=altastata_dot_v1_dot_sharing__pb2.RevokeByQueryRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_sharing__pb2.RevokeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.SharingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.SharingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SharingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Share(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.SharingService/Share',
            altastata_dot_v1_dot_sharing__pb2.ShareRequest.SerializeToString,
            altastata_dot_v1_dot_sharing__pb2.ShareResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.SharingService/Revoke',
            altastata_dot_v1_dot_sharing__pb2.RevokeRequest.SerializeToString,
            altastata_dot_v1_dot_sharing__pb2.RevokeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareByQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.SharingService/ShareByQuery',
            altastata_dot_v1_dot_sharing__pb2.ShareByQueryRequest.SerializeToString,
            altastata_dot_v1_dot_sharing__pb2.ShareResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeByQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.SharingService/RevokeByQuery',
            altastata_dot_v1_dot_sharing__pb2.RevokeByQueryRequest.SerializeToString,
            altastata_dot_v1_dot_sharing__pb2.RevokeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
