# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altastata/v1/sharing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'altastata/v1/sharing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61ltastata/v1/sharing.proto\x12\x0c\x61ltastata.v1\"3\n\x0cShareRequest\x12\x12\n\nfile_paths\x18\x01 \x03(\t\x12\x0f\n\x07readers\x18\x02 \x03(\t\"4\n\rRevokeRequest\x12\x12\n\nfile_paths\x18\x01 \x03(\t\x12\x0f\n\x07readers\x18\x02 \x03(\t\"\x9b\x01\n\x13ShareByQueryRequest\x12\x19\n\x11\x63loud_path_prefix\x18\x01 \x01(\t\x12 \n\x18including_subdirectories\x18\x02 \x01(\x08\x12\x1b\n\x13time_interval_start\x18\x03 \x01(\t\x12\x19\n\x11time_interval_end\x18\x04 \x01(\t\x12\x0f\n\x07readers\x18\x05 \x03(\t\"\x9c\x01\n\x14RevokeByQueryRequest\x12\x19\n\x11\x63loud_path_prefix\x18\x01 \x01(\t\x12 \n\x18including_subdirectories\x18\x02 \x01(\x08\x12\x1b\n\x13time_interval_start\x18\x03 \x01(\t\x12\x19\n\x11time_interval_end\x18\x04 \x01(\t\x12\x0f\n\x07readers\x18\x05 \x03(\t\"G\n\nFileStatus\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x17\n\x0foperation_state\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"9\n\x0bShareResult\x12*\n\x08statuses\x18\x01 \x03(\x0b\x32\x18.altastata.v1.FileStatus\":\n\x0cRevokeResult\x12*\n\x08statuses\x18\x01 \x03(\x0b\x32\x18.altastata.v1.FileStatus2\xb2\x02\n\x0eSharingService\x12>\n\x05Share\x12\x1a.altastata.v1.ShareRequest\x1a\x19.altastata.v1.ShareResult\x12\x41\n\x06Revoke\x12\x1b.altastata.v1.RevokeRequest\x1a\x1a.altastata.v1.RevokeResult\x12L\n\x0cShareByQuery\x12!.altastata.v1.ShareByQueryRequest\x1a\x19.altastata.v1.ShareResult\x12O\n\rRevokeByQuery\x12\".altastata.v1.RevokeByQueryRequest\x1a\x1a.altastata.v1.RevokeResultB*\n\x18\x63om.altastata.grpc.protoB\x0cSharingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altastata.v1.sharing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.altastata.grpc.protoB\014SharingProtoP\001'
  _globals['_SHAREREQUEST']._serialized_start=44
  _globals['_SHAREREQUEST']._serialized_end=95
  _globals['_REVOKEREQUEST']._serialized_start=97
  _globals['_REVOKEREQUEST']._serialized_end=149
  _globals['_SHAREBYQUERYREQUEST']._serialized_start=152
  _globals['_SHAREBYQUERYREQUEST']._serialized_end=307
  _globals['_REVOKEBYQUERYREQUEST']._serialized_start=310
  _globals['_REVOKEBYQUERYREQUEST']._serialized_end=466
  _globals['_FILESTATUS']._serialized_start=468
  _globals['_FILESTATUS']._serialized_end=539
  _globals['_SHARERESULT']._serialized_start=541
  _globals['_SHARERESULT']._serialized_end=598
  _globals['_REVOKERESULT']._serialized_start=600
  _globals['_REVOKERESULT']._serialized_end=658
  _globals['_SHARINGSERVICE']._serialized_start=661
  _globals['_SHARINGSERVICE']._serialized_end=967
# @@protoc_insertion_point(module_scope)
