# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.v1 import users_pb2 as altastata_dot_v1_dot_users__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/v1/users_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_stream(
                '/altastata.v1.UsersService/ListUsers',
                request_serializer=altastata_dot_v1_dot_users__pb2.Empty.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_users__pb2.UserSummary.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/altastata.v1.UsersService/GetUser',
                request_serializer=altastata_dot_v1_dot_users__pb2.GetUserRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_users__pb2.User.FromString,
                _registered_method=True)
        self.GetMyAccount = channel.unary_unary(
                '/altastata.v1.UsersService/GetMyAccount',
                request_serializer=altastata_dot_v1_dot_users__pb2.GetMyAccountRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_users__pb2.User.FromString,
                _registered_method=True)
        self.SetPassword = channel.unary_unary(
                '/altastata.v1.UsersService/SetPassword',
                request_serializer=altastata_dot_v1_dot_users__pb2.SetPasswordRequest.SerializeToString,
                response_deserializer=altastata_dot_v1_dot_users__pb2.SetPasswordResponse.FromString,
                _registered_method=True)


class UsersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=altastata_dot_v1_dot_users__pb2.Empty.FromString,
                    response_serializer=altastata_dot_v1_dot_users__pb2.UserSummary.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=altastata_dot_v1_dot_users__pb2.GetUserRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_users__pb2.User.SerializeToString,
            ),
            'GetMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyAccount,
                    request_deserializer=altastata_dot_v1_dot_users__pb2.GetMyAccountRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_users__pb2.User.SerializeToString,
            ),
            'SetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPassword,
                    request_deserializer=altastata_dot_v1_dot_users__pb2.SetPasswordRequest.FromString,
                    response_serializer=altastata_dot_v1_dot_users__pb2.SetPasswordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.UsersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.UsersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/altastata.v1.UsersService/ListUsers',
            altastata_dot_v1_dot_users__pb2.Empty.SerializeToString,
            altastata_dot_v1_dot_users__pb2.UserSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.UsersService/GetUser',
            altastata_dot_v1_dot_users__pb2.GetUserRequest.SerializeToString,
            altastata_dot_v1_dot_users__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.UsersService/GetMyAccount',
            altastata_dot_v1_dot_users__pb2.GetMyAccountRequest.SerializeToString,
            altastata_dot_v1_dot_users__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.UsersService/SetPassword',
            altastata_dot_v1_dot_users__pb2.SetPasswordRequest.SerializeToString,
            altastata_dot_v1_dot_users__pb2.SetPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
