# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altastata/v1/users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'altastata/v1/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61ltastata/v1/users.proto\x12\x0c\x61ltastata.v1\"\x07\n\x05\x45mpty\"5\n\x0bUserSummary\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0binitialized\x18\x02 \x01(\x08\"B\n\x04User\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0binitialized\x18\x02 \x01(\x08\x12\x12\n\naccess_key\x18\x03 \x01(\t\"#\n\x0eGetUserRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"\x15\n\x13GetMyAccountRequest\".\n\x12SetPasswordRequest\x12\x18\n\x10\x61\x63\x63ount_password\x18\x01 \x01(\t\"&\n\x13SetPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa5\x02\n\x0cUsersService\x12=\n\tListUsers\x12\x13.altastata.v1.Empty\x1a\x19.altastata.v1.UserSummary0\x01\x12;\n\x07GetUser\x12\x1c.altastata.v1.GetUserRequest\x1a\x12.altastata.v1.User\x12\x45\n\x0cGetMyAccount\x12!.altastata.v1.GetMyAccountRequest\x1a\x12.altastata.v1.User\x12R\n\x0bSetPassword\x12 .altastata.v1.SetPasswordRequest\x1a!.altastata.v1.SetPasswordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altastata.v1.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=42
  _globals['_EMPTY']._serialized_end=49
  _globals['_USERSUMMARY']._serialized_start=51
  _globals['_USERSUMMARY']._serialized_end=104
  _globals['_USER']._serialized_start=106
  _globals['_USER']._serialized_end=172
  _globals['_GETUSERREQUEST']._serialized_start=174
  _globals['_GETUSERREQUEST']._serialized_end=209
  _globals['_GETMYACCOUNTREQUEST']._serialized_start=211
  _globals['_GETMYACCOUNTREQUEST']._serialized_end=232
  _globals['_SETPASSWORDREQUEST']._serialized_start=234
  _globals['_SETPASSWORDREQUEST']._serialized_end=280
  _globals['_SETPASSWORDRESPONSE']._serialized_start=282
  _globals['_SETPASSWORDRESPONSE']._serialized_end=320
  _globals['_USERSSERVICE']._serialized_start=323
  _globals['_USERSSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
